### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by ezrqnkemboi**
Just done some designs for my web pages including adding necessary images. 
Need some review. 
Thank you.

### CODE REVIEW

**Comment by Xerrex** [comment]
Awesome.. what is the purpose of the `.idea` folder.?

**Comment by ezrqnkemboi** [comment]
That file is generated by pycharm,

**Comment by faustineomuya** [comment]
On point commit messages. Good job

**Comment by ezrqnkemboi** [comment]
Muya. Thanks.

**Pull request merged**
